# Generated by Django 3.0.2 on 2020-03-01 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='無効な値です'), django.core.validators.MaxValueValidator(31, message='無効な値です')]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='無効な値です'), django.core.validators.MaxValueValidator(12, message='無効な値です')]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(2020, message='無効な値です')]),
        ),
    ]
