# Generated by Django 3.0.2 on 2020-03-01 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_auto_20200301_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2020, message='無効な値です')]),
        ),
    ]
