# Generated by Django 3.0.3 on 2020-05-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0008_weatherforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbabilityOfRain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=4)),
                ('hour', models.CharField(max_length=5)),
                ('prob_rain', models.CharField(max_length=3)),
            ],
        ),
    ]
