# Generated by Django 3.0.3 on 2020-05-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0009_probabilityofrain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='place',
        ),
        migrations.AddField(
            model_name='schedule',
            name='information',
            field=models.CharField(blank=True, choices=[('0.5', '30分前'), ('1', '1時間前'), ('2', '2時間前'), ('3', '3時間前'), ('6', '6時間前'), ('12', '12時間前'), ('24', '24時間前')], max_length=3),
        ),
    ]
