# Generated by Django 3.0.3 on 2020-05-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0012_auto_20200515_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='probabilityofrain',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
