# Generated by Django 3.0.3 on 2020-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0014_schedule_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task_id',
            field=models.CharField(default=None, max_length=36),
        ),
    ]
